/*
 * cmmenums.h
 *
 *  Created on: Sep 23, 2017
 *      Author: hungnv103
 */

#ifndef CMMENUMS_H_
#define CMMENUMS_H_

/*----------------------C125 status-----------------------------------*/
enum C125MessageOpcode{
	///Request from dhl --> c125Adapter
	REQUEST_ASSIGNED_TARGET=100,
	REQUEST_DEASSIGNED_TARGET=101,
	REQUEST_SYSTEM_STATUS=102,
	REQUEST_TRACK_UPDATE=103,
	REQUEST_TRACK_SIMULATION=104,
	REQUEST_UK42_LESSION=105,

	//Request ExTarget
	REQUEST_EXTARGET_START=110,
	REQUEST_EXTARGET_STOP=111,
	REQUEST_EXTARGET_NORMAL=112,
	REQUEST_EXTARGET_IFF=113,
	REQUEST_EXTARGET_HISTORY=114,

	///Reply
	RESPOND_ASSIGNED_DONE=150,
	RESPOND_ASSIGNED_FAILE=152,///Check data for more details
	RESPOND_DEASSIGNED_DONE=153,
	RESPOND_DEASSIGNED_FAILED=154,///Check data for more details
	RESPOND_REQUEST_STATUS=155,///CHeck data for more details
	RESPOND_TRACK_SIMULATION=156,
	RESPOND_UK42_LESSION=157,

	//Reply ExTarget
	RESPOND_EXTARGET_START_DONE = 160,
	RESPOND_EXTARGET_STOP_DONE = 161,
	RESPOND_EXTARGET_NORMAL = 162,
	RESPOND_EXTARGET_IFF = 163,
	RESPOND_EXTARGET_HISTORY_DONE = 164
};

#endif /* CMMENUMS_H_ */
